## A path containing any logs you which to compress. Must be reachable by all
## workers.
## - This path will be exposed inside the container, so symbolic links to files
##   outside this path will be ignored.
#input_logs_directory: "/"
#
## File containing credentials for services
#credentials_file_path: "etc/credentials.yml"
#
#database:
#  type: "mysql"  # "mariadb" or "mysql"
#  # We don't use localhost since MySQL & its connectors interpret that as a
#  # connection on a local socket rather than through the network.
#  host: "127.0.0.1"  
#  port: 3306
#  name: "clp-db"
#
#results_cache:
#  host: "localhost"
#  port: 27017
#  db_name: "clp-search"
#  results_collection_name: "results"
#  metadata_collection_name: "results-metadata"
#
#compression_queue:
#  host: "localhost"
#  port: 5672
#search_queue:
#  host: "localhost"
#  port: 5673
#
#webui_query_handler:
#  host: "localhost"
#  port: 4001
#  max-results: 1000000
#  logging_level: "INFO"
#
#webui:
#  host: "localhost"
#  port: 4000
#
#compression_job_handler:
#  logging_level: "INFO"
#compression_worker:
#  logging_level: "INFO"
#
#search_scheduler:
#  jobs_poll_delay: 0.1  # seconds
#  logging_level: "INFO"
#search_worker:
#  logging_level: "INFO"
#
#reducer:
#  logging_level: "INFO"
#  polling_interval: 100 # milliseconds
#  base_port: 14009
#
## Where archives should be output to
#archive_output:
#  type: "fs"
#  directory: "var/data/archives"
#
#  # How much data CLP should try to compress into each archive
#  target_archive_size: 268435456  # 256 MB
#
#  # How large the dictionaries should be allowed to get before the archive is
#  # closed and a new one is created
#  target_dictionaries_size: 33554432  # 32 MB
#
#  # How large each encoded file should be before being split into a new encoded
#  # file
#  target_encoded_file_size: 268435456  # 256 MB
#
#  # How much data CLP should try to fit into each segment within an archive
#  target_segment_size: 268435456  # 256 MB
#
## Location where other data (besides archives) are stored. It will be created if
## it doesn't exist.
#data_directory: "var/data"
#
## Location where logs are stored. It will be created if it doesn't exist.
#logs_directory: "var/log"
